name: dumper

on:
  workflow_dispatch:
    inputs:
      FILE_LINK:
        description: 'Firmware Link'
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS2.0.203.0.VMRMIXM/marble_global-ota_full-OS2.0.203.0.VMRMIXM-user-15.0-22893f0590.zip'
      DEVICE_BRANCH:
        description: 'your device Firmware version.'
        required: true
        default: 'android-16'
      GITHUB_TOKEN:
        description: 'your github personal Access Aoken (classic)'
        required: true
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXX'
      EMPTY_REPO:
        description: 'your empty repo name on github'
        required: true
        default: 'android_device_samsung_a05s.git'
      COMMIT_MESSAGE:
        description: 'your commit message '
        required: true
        default: 'your device name'
        
jobs:
  build:
    name: Dumping by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Getting tools ready !
      run: |
        git clone https://github.com/DumprX/DumprX.git
        cd DumprX
        sudo ./setup.sh
    - name: Download and extracting !
      run: |
        cd DumprX
        ./dumper.sh ${{ github.event.inputs.FILE_LINK }}
        cd out
        ls -la
        rm -rf system
        rm -rf system_ext
        rm -rf mi_ext
        rm -rf modem
        rm -rf product
        rm -rf odm
        
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Push to GitHub
      run: |
          git config --global user.email "Samuel Kendall"
          git config --global user.name "kinguser981@gmail.com"
          cd ./DumprX/out/
          git init
          git config --global http.postBuffer 5368709120
          git add *
          git commit -m "${{ github.event.inputs.COMMIT_MESSAGE }}"
          git branch -M ${{ github.event.inputs.DEVICE_BRANCH }}
          git remote add origin git@github.com:${{ github.actor }}/${{ github.event.inputs.EMPTY_REPO }}
          git remote set-url origin https://${{ github.actor }}:${{ github.event.inputs.GITHUB_TOKEN }}@github.com/${{ github.actor }}/${{ github.event.inputs.EMPTY_REPO }}
          git push -u origin ${{ github.event.inputs.DEVICE_BRANCH }}
    - name: Add to Github release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.COMMIT_MESSAGE }} // ${{ env.BUILD_DATE }} 
        tag_name: Extracted Firmware Link https://github.com/${{ github.actor }}/${{ github.event.inputs.EMPTY_REPO }} 
        body: |
